{
    "name": "Custom Background",
    "version": "14.0.0.0.10",
    "author": "BizzAppDev",
    "website": "http://www.bizzappdev.com",
    "category": "GenericModules",
    "depends": ["base", "web"],
    "summary": "Custom  Background",
    "images": ['images/image.png'],
    "init_xml": [],
    "data": [
        "security/ir.model.access.csv",
        "views/ir_actions.xml",
        "views/res_company_view.xml",
        "views/report_template.xml",
    ],
    "demo_xml": [],
    "test": [],
    "installable": True,
    "application": False,
    "license": "Other proprietary",
}
